version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "orders-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-89d7to63m1lv"
s3_prefix = "orders-api"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
